module.exports = function () {
    return {
        "lolomo" : { "$type": "path", "value": ["lolomos", "123"] },
        "lolomos": { "123": {
            "0": { "$type": "path", "value": ["lists", "012"] },
            "1": { "$type": "path", "value": ["lists", "123"] },
            "2": { "$type": "path", "value": ["lists", "234"] },
            "3": { "$type": "path", "value": ["lists", "345"] },
            "4": { "$type": "path", "value": ["lists", "456"] },
            "5": { "$type": "path", "value": ["lists", "567"] },
            "6": { "$type": "path", "value": ["lists", "678"] },
            "7": { "$type": "path", "value": ["lists", "789"] },
            "8": { "$type": "path", "value": ["lists", "890"] },
            "9": { "$type": "path", "value": ["lists", "901"] },
        } },
        "lists"  : {
            "012": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "123": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "234": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "345": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "456": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "567": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "678": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "789": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "890": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
            "901": {
                "0": { "$type": "path", "value": ["recommendations", "012"] },
                "1": { "$type": "path", "value": ["recommendations", "123"] },
                "2": { "$type": "path", "value": ["recommendations", "234"] },
                "3": { "$type": "path", "value": ["recommendations", "345"] },
                "4": { "$type": "path", "value": ["recommendations", "456"] },
                "5": { "$type": "path", "value": ["recommendations", "567"] },
                "6": { "$type": "path", "value": ["recommendations", "678"] },
                "7": { "$type": "path", "value": ["recommendations", "789"] },
                "8": { "$type": "path", "value": ["recommendations", "890"] },
                "9": { "$type": "path", "value": ["recommendations", "901"] },
            },
        },
        "recommendations"  : {
            "012": { "item": { "$type": "path", "value": ["videos", "012"] } },
            "123": { "item": { "$type": "path", "value": ["videos", "123"] } },
            "234": { "item": { "$type": "path", "value": ["videos", "234"] } },
            "345": { "item": { "$type": "path", "value": ["videos", "345"] } },
            "456": { "item": { "$type": "path", "value": ["videos", "456"] } },
            "567": { "item": { "$type": "path", "value": ["videos", "567"] } },
            "678": { "item": { "$type": "path", "value": ["videos", "678"] } },
            "789": { "item": { "$type": "path", "value": ["videos", "789"] } },
            "890": { "item": { "$type": "path", "value": ["videos", "890"] } },
            "901": { "item": { "$type": "path", "value": ["videos", "901"] } },
        },
        "videos" : {
            "012": { "summary": { "$type": "sentinel", "value": "012" } },
            "123": { "summary": { "$type": "sentinel", "value": "123" } },
            "234": { "summary": { "$type": "sentinel", "value": "234" } },
            "345": { "summary": { "$type": "sentinel", "value": "345" } },
            "456": { "summary": { "$type": "sentinel", "value": "456" } },
            "567": { "summary": { "$type": "sentinel", "value": "567" } },
            "678": { "summary": { "$type": "sentinel", "value": "678" } },
            "789": { "summary": { "$type": "sentinel", "value": "789" } },
            "890": { "summary": { "$type": "sentinel", "value": "890" } },
            "901": { "summary": { "$type": "sentinel", "value": "901" } },
        }
    };
}
